apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
  - image: nmbiyu/auth
    context: auth
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: nmbiyu/client
    context: client
    sync:
      manual:
      - src: src/**/*.js
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: nmbiyu/tickets
    context: tickets
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: nmbiyu/orders
    context: orders
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: nmbiyu/expiration
    context: expiration
    sync:
      manual:
        - src: src/**/*.ts
          dest: .
    docker:
      dockerfile: Dockerfile
  # Local build config for the minikube context
  local:
    push: false
  # Google cloud config
  #googleCloudBuild:
    #projectId: ticketing-dev-379109
manifests:
  rawYaml:
  - ./infra/k8s/*
deploy:
  kubectl: {}
