#!/bin/bash
services=("auth" "expiration" "orders" "payments" "tickets")
for service in "${services[@]}"
do
  pushd "$service" || exit
  echo "Updating @nmbiyutickets/common in ${service} service..."
  npm update @nmbiyutickets/common
  popd
done
