apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../k8s
patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: nmbiyu.dev
    target:
      name: ingress-service