name: deploy-tickets

on:
  push:
    branches:
      - master
    paths:
      - 'tickets/**'

jobs:
  build:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: tickets
      PROJECT_ID: ticketing-dev-379109
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: 'github-service-account@ticketing-dev-379109.iam.gserviceaccount.com'
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: '>= 363.0.0'

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest tickets

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Push Docker Image to Container Registry (GCR)
        env:
          GIT_TAG: v0.1.0
        run: |-
          docker tag $IMAGE_NAME:latest us.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest us.gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push us.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push us.gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

#      - name: Restart deployment
#        run: kubectl rollout restart deployment tickets-depl -n default


#      - name: Push Docker Image to Artifact Registry
#        env:
#          GIT_TAG: v0.1.0
#        run: |-
#          docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:latest
#          docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
#          docker push us-central1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:latest
#          docker push us-central1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG