name: deploy-auth

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: auth
      PROJECT_ID: ticketing-dev-379109
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: 'github-service-account@ticketing-dev-379109.iam.gserviceaccount.com'
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: '>= 363.0.0'

      - run: kubectl apply -f infra/k8s
